services:
  httpd:
    build:
      context: ..
      dockerfile: container/Containerfile.linux
    image: apache-http3-dev:latest
    container_name: mod_http3_dev
    ports:
      - "8443:8443/tcp"   # HTTP/1.1 and HTTP/2
      - "8443:8443/udp"   # HTTP/3
    volumes:
      # Optionally override the default configuration and certificates by mounting your own files.
      #
      # - ./httpd-linux.conf:/src/dependencies/httpd-dist/conf/httpd.conf:ro
      # - ./certs:/src/dependencies/httpd-dist/conf/certs:ro
      # - ./static:/src/dependencies/httpd-dist/htdocs:ro
    healthcheck:
      test: ["CMD", "curl", "--http3", "-ksSf", "https://localhost:8443/"]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: on-failure:3
    security_opt:
      - label:disable
